// The shipped exercise library — reference data, not user data.
//
// Schema per exercise:
//   id                unique slug
//   name              display name
//   movementPattern   one of MOVEMENT_PATTERNS
//   primaryMuscles    muscles doing most of the work
//   secondaryMuscles  meaningfully involved, but not the point of the lift
//   equipment         tokens from EQUIPMENT; a location must have ALL of them
//   locations         where this is actually worth doing ("Work" / "Home")
//   variationGroup    close variants share a group so freshness can rotate
//                     between families rather than between near-identical lifts
//   tier              'primary'   — heavy compound, goes first
//                     'secondary' — compound accessory
//                     'accessory' — isolation / low-skill finisher
//   capFriendly       true when the lift stays genuinely hard under Home's
//                     load caps (see LOCATION_LOAD_CAPS)
//   capStrategy       WHY it stays hard: 'unilateral' | 'tempo' | 'highRep' |
//                     'elevatedRange'. Null for lifts that simply don't need
//                     much load, or that aren't cap-limited at all.
//   loadNotes         free text, shown in the UI when a weight cap is relevant
//
// `capFriendly` / `capStrategy` exist so the generator can prefer the right
// Home variations from DATA rather than the UI hardcoding "if Home and squat
// then ...". Adding a new cap-beating variation is a data edit, not a code
// change.

export const MOVEMENT_PATTERNS = [
  'squat',
  'hinge',
  'horizontalPush',
  'verticalPush',
  'horizontalPull',
  'verticalPull',
  'unilateral',
  'core',
  'carry',
];

// Human-readable labels for the pattern tokens above.
export const PATTERN_LABELS = {
  squat: 'Squat',
  hinge: 'Hinge',
  horizontalPush: 'Horizontal Push',
  verticalPush: 'Vertical Push',
  horizontalPull: 'Horizontal Pull',
  verticalPull: 'Vertical Pull',
  unilateral: 'Lunge / Unilateral',
  core: 'Core',
  carry: 'Carry',
};

export const EQUIPMENT = [
  'barbell',
  'dumbbells',
  'bench',
  'machine',
  'cable',
  'bodyweight',
  'rack',
  'pullupBar',
];

// What each location physically has. Mirrors the `equipment` collection seeded
// in seed.js — kept as flat tokens here because that is what filtering needs.
export const LOCATION_EQUIPMENT = {
  Work: ['barbell', 'dumbbells', 'bench', 'machine', 'cable', 'bodyweight', 'rack', 'pullupBar'],
  Home: ['barbell', 'dumbbells', 'bench', 'bodyweight'],
};

// Load ceilings per location. null = no meaningful cap.
export const LOCATION_LOAD_CAPS = {
  Work: { dumbbellPerHand: null, barbellTotal: null },
  Home: { dumbbellPerHand: 52.5, barbellTotal: 80 },
};

// The smallest real weight change available, per location and load type.
//
// Progression is worthless if it suggests a weight the equipment cannot make.
// Home's adjustable dumbbells move in 2.5 lb steps per hand; its adjustable
// barbell and curl bar take plates in 5 lb total increments. Work is a full
// gym: fixed dumbbells in 5 lb jumps, barbell in 5 lb total (2.5 a side), and
// machine stacks in 10 lb pins.
//
// Data rather than logic, same as the caps above: changing a rack is an edit
// here, not a code change.
export const LOCATION_LOAD_STEPS = {
  Work: { dumbbellPerHand: 5, barbellTotal: 5, machine: 10, cable: 5 },
  Home: { dumbbellPerHand: 2.5, barbellTotal: 5, machine: null, cable: null },
};

/**
 * Which load ceiling and step size govern this exercise.
 *
 * Returns null for bodyweight-only movements, which progress by reps rather
 * than by load — suggesting "+5 lb" on a Dead Bug helps nobody.
 */
export function loadKindFor(exercise) {
  const equipment = exercise?.equipment ?? [];
  if (equipment.includes('barbell')) return 'barbellTotal';
  if (equipment.includes('dumbbells')) return 'dumbbellPerHand';
  if (equipment.includes('machine')) return 'machine';
  if (equipment.includes('cable')) return 'cable';
  return null;
}

// Patterns where Home's 80 lb barbell / 52.5 lb dumbbells are the binding
// constraint — a straight bilateral set would just be too light to be worth
// doing. The generator prefers capFriendly options for these at Home.
export const CAP_SENSITIVE_PATTERNS = ['squat', 'hinge', 'unilateral'];

// Human-readable capStrategy labels for the UI — the raw tokens are camelCase
// identifiers and should never be shown to a person.
export const CAP_STRATEGY_LABELS = {
  unilateral: 'one side at a time',
  tempo: 'tempo',
  highRep: 'high rep',
  elevatedRange: 'extra range',
};

export const seedExerciseLibrary = [
  // ---------------------------------------------------------------- SQUAT
  {
    id: 'back-squat',
    name: 'Back Squat',
    movementPattern: 'squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['adductors', 'spinal erectors', 'core'],
    equipment: ['barbell', 'rack'],
    locations: ['Work'],
    variationGroup: 'back-squat',
    tier: 'primary',
  },
  {
    id: 'pause-back-squat',
    name: 'Paused Back Squat',
    movementPattern: 'squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['adductors', 'core'],
    equipment: ['barbell', 'rack'],
    locations: ['Work'],
    variationGroup: 'back-squat',
    tier: 'primary',
    capStrategy: 'tempo',
  },
  {
    id: 'box-squat',
    name: 'Box Squat',
    movementPattern: 'squat',
    primaryMuscles: ['glutes', 'quads'],
    secondaryMuscles: ['hamstrings', 'core'],
    equipment: ['barbell', 'rack', 'bench'],
    locations: ['Work'],
    variationGroup: 'back-squat',
    tier: 'primary',
  },
  {
    id: 'front-squat',
    name: 'Front Squat',
    movementPattern: 'squat',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes', 'upper back', 'core'],
    equipment: ['barbell', 'rack'],
    locations: ['Work'],
    variationGroup: 'front-squat',
    tier: 'primary',
  },
  {
    id: 'tempo-front-squat',
    name: 'Tempo Front Squat (3s down, 1s pause)',
    movementPattern: 'squat',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes', 'core'],
    equipment: ['barbell'],
    locations: ['Work', 'Home'],
    variationGroup: 'front-squat',
    tier: 'primary',
    capFriendly: true,
    capStrategy: 'tempo',
    loadNotes:
      'At Home the bar caps at 80 lb total — the slow eccentric and pause are what make this hard, not the load. Chase time under tension, not weight.',
  },
  {
    id: 'goblet-squat',
    name: 'Goblet Squat',
    movementPattern: 'squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['core', 'upper back'],
    equipment: ['dumbbells'],
    locations: ['Work', 'Home'],
    variationGroup: 'goblet-squat',
    tier: 'secondary',
    capFriendly: true,
    loadNotes: 'A single 52.5 lb dumbbell is plenty here — this is rarely load-limited.',
  },
  {
    id: 'tempo-goblet-squat',
    name: 'Tempo Goblet Squat (4s down)',
    movementPattern: 'squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['core'],
    equipment: ['dumbbells'],
    locations: ['Work', 'Home'],
    variationGroup: 'goblet-squat',
    tier: 'secondary',
    capFriendly: true,
    capStrategy: 'tempo',
    loadNotes: 'Slow the eccentric to make the capped load bite.',
  },
  {
    id: 'heels-elevated-goblet-squat',
    name: 'Heels-Elevated Goblet Squat',
    movementPattern: 'squat',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes', 'core'],
    equipment: ['dumbbells'],
    locations: ['Work', 'Home'],
    variationGroup: 'goblet-squat',
    tier: 'secondary',
    capFriendly: true,
    capStrategy: 'elevatedRange',
    loadNotes: 'Elevating the heels deepens the knee bend, so less load is needed for the same quad stimulus.',
  },
  {
    id: 'dumbbell-squat',
    name: 'Dumbbell Squat',
    movementPattern: 'squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['core', 'forearms'],
    equipment: ['dumbbells'],
    locations: ['Work', 'Home'],
    variationGroup: 'dumbbell-squat',
    tier: 'secondary',
    loadNotes: 'Grip and the 52.5 lb/hand cap become the limit before the legs do — pair with higher reps.',
  },
  {
    id: 'hack-squat-machine',
    name: 'Hack Squat (Machine)',
    movementPattern: 'squat',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes'],
    equipment: ['machine'],
    locations: ['Work'],
    variationGroup: 'machine-squat',
    tier: 'secondary',
  },
  {
    id: 'leg-press',
    name: 'Leg Press',
    movementPattern: 'squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['adductors'],
    equipment: ['machine'],
    locations: ['Work'],
    variationGroup: 'machine-squat',
    tier: 'secondary',
  },

  // ---------------------------------------------------------------- HINGE
  {
    id: 'conventional-deadlift',
    name: 'Conventional Deadlift',
    movementPattern: 'hinge',
    primaryMuscles: ['glutes', 'hamstrings', 'spinal erectors'],
    secondaryMuscles: ['lats', 'traps', 'forearms'],
    equipment: ['barbell'],
    locations: ['Work'],
    variationGroup: 'deadlift',
    tier: 'primary',
  },
  {
    id: 'trap-bar-style-dumbbell-deadlift',
    name: 'Dumbbell Deadlift',
    movementPattern: 'hinge',
    primaryMuscles: ['glutes', 'hamstrings'],
    secondaryMuscles: ['quads', 'forearms'],
    equipment: ['dumbbells'],
    locations: ['Work', 'Home'],
    variationGroup: 'deadlift',
    tier: 'secondary',
    loadNotes: 'Caps out fast at 52.5 lb/hand — treat as a higher-rep hinge, not a max-effort pull.',
    capStrategy: 'highRep',
  },
  {
    id: 'barbell-rdl',
    name: 'Romanian Deadlift (Barbell)',
    movementPattern: 'hinge',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['spinal erectors', 'lats'],
    equipment: ['barbell'],
    locations: ['Work'],
    variationGroup: 'rdl',
    tier: 'primary',
  },
  {
    id: 'dumbbell-rdl',
    name: 'Dumbbell Romanian Deadlift',
    movementPattern: 'hinge',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['spinal erectors'],
    equipment: ['dumbbells'],
    locations: ['Work', 'Home'],
    variationGroup: 'rdl',
    tier: 'secondary',
    loadNotes: '105 lb of dumbbells is light for a bilateral RDL — slow the eccentric or go single-leg.',
  },
  {
    id: 'tempo-dumbbell-rdl',
    name: 'Tempo Dumbbell RDL (4s down)',
    movementPattern: 'hinge',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['spinal erectors'],
    equipment: ['dumbbells'],
    locations: ['Work', 'Home'],
    variationGroup: 'rdl',
    tier: 'secondary',
    capFriendly: true,
    capStrategy: 'tempo',
    loadNotes: 'The 4s eccentric makes capped dumbbells feel heavy — do not rush the descent.',
  },
  {
    id: 'single-leg-rdl',
    name: 'Single-Leg RDL',
    movementPattern: 'hinge',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['spinal erectors', 'core'],
    equipment: ['dumbbells'],
    locations: ['Work', 'Home'],
    variationGroup: 'single-leg-rdl',
    tier: 'secondary',
    capFriendly: true,
    capStrategy: 'unilateral',
    loadNotes: 'One leg at a time halves the load needed — ideal under the Home cap.',
  },
  {
    id: 'b-stance-rdl',
    name: 'B-Stance RDL',
    movementPattern: 'hinge',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['core'],
    equipment: ['dumbbells'],
    locations: ['Work', 'Home'],
    variationGroup: 'single-leg-rdl',
    tier: 'secondary',
    capFriendly: true,
    capStrategy: 'unilateral',
    loadNotes: 'Most of the load sits on the front leg while the back toe just balances.',
  },
  {
    id: 'barbell-hip-thrust',
    name: 'Barbell Hip Thrust',
    movementPattern: 'hinge',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['barbell', 'bench'],
    locations: ['Work'],
    variationGroup: 'hip-thrust',
    tier: 'secondary',
  },
  {
    id: 'single-leg-hip-thrust',
    name: 'Single-Leg Hip Thrust',
    movementPattern: 'hinge',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'core'],
    equipment: ['bench', 'bodyweight'],
    locations: ['Work', 'Home'],
    variationGroup: 'hip-thrust',
    tier: 'secondary',
    capFriendly: true,
    capStrategy: 'unilateral',
    loadNotes: 'Bodyweight on one leg is already hard; add a dumbbell on the hip once easy.',
  },
  {
    id: 'dumbbell-hip-thrust',
    name: 'Dumbbell Hip Thrust',
    movementPattern: 'hinge',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['dumbbells', 'bench'],
    locations: ['Work', 'Home'],
    variationGroup: 'hip-thrust',
    tier: 'secondary',
    capStrategy: 'highRep',
    loadNotes: 'Glutes outgrow a 52.5 lb dumbbell quickly — run high reps or switch to single-leg.',
  },
  {
    id: 'good-morning',
    name: 'Good Morning',
    movementPattern: 'hinge',
    primaryMuscles: ['hamstrings', 'spinal erectors'],
    secondaryMuscles: ['glutes'],
    equipment: ['barbell', 'rack'],
    locations: ['Work'],
    variationGroup: 'good-morning',
    tier: 'secondary',
  },
  {
    id: 'back-extension',
    name: 'Back Extension',
    movementPattern: 'hinge',
    primaryMuscles: ['spinal erectors', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['machine'],
    locations: ['Work'],
    variationGroup: 'back-extension',
    tier: 'accessory',
  },
  {
    id: 'dumbbell-swing',
    name: 'Dumbbell Swing',
    movementPattern: 'hinge',
    primaryMuscles: ['glutes', 'hamstrings'],
    secondaryMuscles: ['core', 'shoulders'],
    equipment: ['dumbbells'],
    locations: ['Work', 'Home'],
    variationGroup: 'swing',
    tier: 'accessory',
    capFriendly: true,
    capStrategy: 'highRep',
    loadNotes: 'Ballistic and rep-driven — the cap is irrelevant here.',
  },

  // ------------------------------------------------------- HORIZONTAL PUSH
  {
    id: 'barbell-bench-press',
    name: 'Barbell Bench Press',
    movementPattern: 'horizontalPush',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'front delts'],
    equipment: ['barbell', 'bench', 'rack'],
    locations: ['Work'],
    variationGroup: 'flat-press',
    tier: 'primary',
  },
  {
    id: 'dumbbell-bench-press',
    name: 'Dumbbell Bench Press',
    movementPattern: 'horizontalPush',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'front delts'],
    equipment: ['dumbbells', 'bench'],
    locations: ['Work', 'Home'],
    variationGroup: 'flat-press',
    tier: 'primary',
  },
  {
    id: 'tempo-dumbbell-bench-press',
    name: 'Tempo Dumbbell Bench Press (3s down)',
    movementPattern: 'horizontalPush',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps'],
    equipment: ['dumbbells', 'bench'],
    locations: ['Work', 'Home'],
    variationGroup: 'flat-press',
    tier: 'primary',
    capStrategy: 'tempo',
  },
  {
    id: 'dumbbell-floor-press',
    name: 'Dumbbell Floor Press',
    movementPattern: 'horizontalPush',
    primaryMuscles: ['chest', 'triceps'],
    secondaryMuscles: ['front delts'],
    equipment: ['dumbbells'],
    locations: ['Work', 'Home'],
    variationGroup: 'flat-press',
    tier: 'secondary',
  },
  {
    id: 'incline-barbell-press',
    name: 'Incline Barbell Press',
    movementPattern: 'horizontalPush',
    primaryMuscles: ['upper chest'],
    secondaryMuscles: ['front delts', 'triceps'],
    equipment: ['barbell', 'bench', 'rack'],
    locations: ['Work'],
    variationGroup: 'incline-press',
    tier: 'primary',
  },
  {
    id: 'incline-dumbbell-press',
    name: 'Incline Dumbbell Press',
    movementPattern: 'horizontalPush',
    primaryMuscles: ['upper chest'],
    secondaryMuscles: ['front delts', 'triceps'],
    equipment: ['dumbbells', 'bench'],
    locations: ['Work', 'Home'],
    variationGroup: 'incline-press',
    tier: 'primary',
  },
  {
    id: 'push-up',
    name: 'Push-Up',
    movementPattern: 'horizontalPush',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'core'],
    equipment: ['bodyweight'],
    locations: ['Work', 'Home'],
    variationGroup: 'push-up',
    tier: 'secondary',
    capFriendly: true,
  },
  {
    id: 'feet-elevated-push-up',
    name: 'Feet-Elevated Push-Up',
    movementPattern: 'horizontalPush',
    primaryMuscles: ['upper chest'],
    secondaryMuscles: ['triceps', 'core'],
    equipment: ['bodyweight', 'bench'],
    locations: ['Work', 'Home'],
    variationGroup: 'push-up',
    tier: 'secondary',
    capFriendly: true,
    capStrategy: 'elevatedRange',
  },
  {
    id: 'deficit-push-up',
    name: 'Deficit Push-Up (hands on dumbbells)',
    movementPattern: 'horizontalPush',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps'],
    equipment: ['bodyweight', 'dumbbells'],
    locations: ['Work', 'Home'],
    variationGroup: 'push-up',
    tier: 'secondary',
    capFriendly: true,
    capStrategy: 'elevatedRange',
  },
  {
    id: 'machine-chest-press',
    name: 'Machine Chest Press',
    movementPattern: 'horizontalPush',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps'],
    equipment: ['machine'],
    locations: ['Work'],
    variationGroup: 'machine-press',
    tier: 'secondary',
  },
  {
    id: 'cable-fly',
    name: 'Cable Fly',
    movementPattern: 'horizontalPush',
    primaryMuscles: ['chest'],
    secondaryMuscles: [],
    equipment: ['cable'],
    locations: ['Work'],
    variationGroup: 'fly',
    tier: 'accessory',
  },
  {
    id: 'dumbbell-fly',
    name: 'Dumbbell Fly',
    movementPattern: 'horizontalPush',
    primaryMuscles: ['chest'],
    secondaryMuscles: [],
    equipment: ['dumbbells', 'bench'],
    locations: ['Work', 'Home'],
    variationGroup: 'fly',
    tier: 'accessory',
  },

  // --------------------------------------------------------- VERTICAL PUSH
  {
    id: 'barbell-overhead-press',
    name: 'Standing Barbell Overhead Press',
    movementPattern: 'verticalPush',
    primaryMuscles: ['front delts'],
    secondaryMuscles: ['triceps', 'upper chest', 'core'],
    equipment: ['barbell', 'rack'],
    locations: ['Work'],
    variationGroup: 'barbell-overhead-press',
    tier: 'primary',
  },
  {
    id: 'seated-dumbbell-shoulder-press',
    name: 'Seated Dumbbell Shoulder Press',
    movementPattern: 'verticalPush',
    primaryMuscles: ['front delts', 'side delts'],
    secondaryMuscles: ['triceps'],
    equipment: ['dumbbells', 'bench'],
    locations: ['Work', 'Home'],
    variationGroup: 'dumbbell-overhead-press',
    tier: 'primary',
  },
  {
    id: 'standing-dumbbell-press',
    name: 'Standing Dumbbell Press',
    movementPattern: 'verticalPush',
    primaryMuscles: ['front delts'],
    secondaryMuscles: ['triceps', 'core'],
    equipment: ['dumbbells'],
    locations: ['Work', 'Home'],
    variationGroup: 'dumbbell-overhead-press',
    tier: 'primary',
  },
  {
    id: 'arnold-press',
    name: 'Arnold Press',
    movementPattern: 'verticalPush',
    primaryMuscles: ['front delts', 'side delts'],
    secondaryMuscles: ['triceps'],
    equipment: ['dumbbells', 'bench'],
    locations: ['Work', 'Home'],
    variationGroup: 'dumbbell-overhead-press',
    tier: 'secondary',
  },
  {
    id: 'half-kneeling-dumbbell-press',
    name: 'Half-Kneeling Single-Arm Press',
    movementPattern: 'verticalPush',
    primaryMuscles: ['front delts'],
    secondaryMuscles: ['core', 'triceps'],
    equipment: ['dumbbells'],
    locations: ['Work', 'Home'],
    variationGroup: 'single-arm-overhead-press',
    tier: 'secondary',
    capFriendly: true,
    capStrategy: 'unilateral',
  },
  {
    id: 'machine-shoulder-press',
    name: 'Machine Shoulder Press',
    movementPattern: 'verticalPush',
    primaryMuscles: ['front delts'],
    secondaryMuscles: ['triceps'],
    equipment: ['machine'],
    locations: ['Work'],
    variationGroup: 'machine-overhead-press',
    tier: 'secondary',
  },
  {
    id: 'pike-push-up',
    name: 'Pike Push-Up',
    movementPattern: 'verticalPush',
    primaryMuscles: ['front delts'],
    secondaryMuscles: ['triceps', 'core'],
    equipment: ['bodyweight'],
    locations: ['Work', 'Home'],
    variationGroup: 'pike-push-up',
    tier: 'secondary',
    capFriendly: true,
  },
  {
    id: 'lateral-raise',
    name: 'Lateral Raise',
    movementPattern: 'verticalPush',
    primaryMuscles: ['side delts'],
    secondaryMuscles: [],
    equipment: ['dumbbells'],
    locations: ['Work', 'Home'],
    variationGroup: 'lateral-raise',
    tier: 'accessory',
    capFriendly: true,
    capStrategy: 'highRep',
  },

  // ------------------------------------------------------- HORIZONTAL PULL
  {
    id: 'barbell-bent-over-row',
    name: 'Barbell Bent-Over Row',
    movementPattern: 'horizontalPull',
    primaryMuscles: ['lats', 'mid back'],
    secondaryMuscles: ['biceps', 'spinal erectors'],
    equipment: ['barbell'],
    locations: ['Work'],
    variationGroup: 'barbell-row',
    tier: 'primary',
  },
  {
    id: 'pendlay-row',
    name: 'Pendlay Row',
    movementPattern: 'horizontalPull',
    primaryMuscles: ['mid back', 'lats'],
    secondaryMuscles: ['biceps'],
    equipment: ['barbell'],
    locations: ['Work'],
    variationGroup: 'barbell-row',
    tier: 'primary',
  },
  {
    id: 'one-arm-dumbbell-row',
    name: 'One-Arm Dumbbell Row',
    movementPattern: 'horizontalPull',
    primaryMuscles: ['lats', 'mid back'],
    secondaryMuscles: ['biceps', 'rear delts'],
    equipment: ['dumbbells', 'bench'],
    locations: ['Work', 'Home'],
    variationGroup: 'single-arm-row',
    tier: 'primary',
    capFriendly: true,
    capStrategy: 'unilateral',
    loadNotes: 'One arm at a time means 52.5 lb is a real working weight.',
  },
  {
    id: 'chest-supported-dumbbell-row',
    name: 'Chest-Supported Dumbbell Row',
    movementPattern: 'horizontalPull',
    primaryMuscles: ['mid back', 'lats'],
    secondaryMuscles: ['rear delts', 'biceps'],
    equipment: ['dumbbells', 'bench'],
    locations: ['Work', 'Home'],
    variationGroup: 'chest-supported-row',
    tier: 'secondary',
  },
  {
    id: 'tempo-chest-supported-row',
    name: 'Tempo Chest-Supported Row (2s hold)',
    movementPattern: 'horizontalPull',
    primaryMuscles: ['mid back'],
    secondaryMuscles: ['rear delts', 'biceps'],
    equipment: ['dumbbells', 'bench'],
    locations: ['Work', 'Home'],
    variationGroup: 'chest-supported-row',
    tier: 'secondary',
    capFriendly: true,
    capStrategy: 'tempo',
    loadNotes: 'Hold the squeeze for 2s at the top — turns a light load into hard work.',
  },
  {
    id: 'seated-cable-row',
    name: 'Seated Cable Row',
    movementPattern: 'horizontalPull',
    primaryMuscles: ['mid back', 'lats'],
    secondaryMuscles: ['biceps'],
    equipment: ['cable'],
    locations: ['Work'],
    variationGroup: 'cable-row',
    tier: 'secondary',
  },
  {
    id: 'machine-row',
    name: 'Machine Row',
    movementPattern: 'horizontalPull',
    primaryMuscles: ['mid back'],
    secondaryMuscles: ['lats', 'biceps'],
    equipment: ['machine'],
    locations: ['Work'],
    variationGroup: 'machine-row',
    tier: 'secondary',
  },
  {
    id: 'inverted-row',
    name: 'Inverted Row',
    movementPattern: 'horizontalPull',
    primaryMuscles: ['mid back'],
    secondaryMuscles: ['biceps', 'core'],
    equipment: ['rack', 'bodyweight'],
    locations: ['Work'],
    variationGroup: 'inverted-row',
    tier: 'secondary',
    capFriendly: true,
  },
  {
    id: 'rear-delt-fly',
    name: 'Rear Delt Fly',
    movementPattern: 'horizontalPull',
    primaryMuscles: ['rear delts'],
    secondaryMuscles: ['mid back'],
    equipment: ['dumbbells'],
    locations: ['Work', 'Home'],
    variationGroup: 'rear-delt-fly',
    tier: 'accessory',
    capFriendly: true,
    capStrategy: 'highRep',
  },

  // --------------------------------------------------------- VERTICAL PULL
  {
    id: 'pull-up',
    name: 'Pull-Up',
    movementPattern: 'verticalPull',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['biceps', 'core'],
    equipment: ['pullupBar', 'bodyweight'],
    locations: ['Work'],
    variationGroup: 'pull-up',
    tier: 'primary',
    capFriendly: true,
  },
  {
    id: 'chin-up',
    name: 'Chin-Up',
    movementPattern: 'verticalPull',
    primaryMuscles: ['lats', 'biceps'],
    secondaryMuscles: ['core'],
    equipment: ['pullupBar', 'bodyweight'],
    locations: ['Work'],
    variationGroup: 'pull-up',
    tier: 'primary',
    capFriendly: true,
  },
  {
    id: 'lat-pulldown',
    name: 'Lat Pulldown',
    movementPattern: 'verticalPull',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['biceps'],
    equipment: ['machine'],
    locations: ['Work'],
    variationGroup: 'pulldown',
    tier: 'primary',
  },
  {
    id: 'half-kneeling-single-arm-pulldown',
    name: 'Half-Kneeling Single-Arm Pulldown',
    movementPattern: 'verticalPull',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['core', 'biceps'],
    equipment: ['cable'],
    locations: ['Work'],
    variationGroup: 'pulldown',
    tier: 'secondary',
    capStrategy: 'unilateral',
  },
  {
    id: 'straight-arm-pulldown',
    name: 'Straight-Arm Pulldown',
    movementPattern: 'verticalPull',
    primaryMuscles: ['lats'],
    secondaryMuscles: [],
    equipment: ['cable'],
    locations: ['Work'],
    variationGroup: 'straight-arm-pulldown',
    tier: 'accessory',
  },
  {
    id: 'dumbbell-pullover',
    name: 'Dumbbell Pullover',
    movementPattern: 'verticalPull',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['chest', 'triceps'],
    equipment: ['dumbbells', 'bench'],
    locations: ['Work', 'Home'],
    variationGroup: 'pullover',
    tier: 'secondary',
    capFriendly: true,
    loadNotes:
      'The only true vertical pull available at Home — there is no pull-up bar in the seeded Home equipment.',
  },
  {
    id: 'tempo-dumbbell-pullover',
    name: 'Tempo Dumbbell Pullover (3s stretch)',
    movementPattern: 'verticalPull',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['chest'],
    equipment: ['dumbbells', 'bench'],
    locations: ['Work', 'Home'],
    variationGroup: 'pullover',
    tier: 'secondary',
    capFriendly: true,
    capStrategy: 'tempo',
  },

  // ------------------------------------------------------ LUNGE/UNILATERAL
  {
    id: 'walking-lunge',
    name: 'Walking Lunge',
    movementPattern: 'unilateral',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'core'],
    equipment: ['dumbbells'],
    locations: ['Work', 'Home'],
    variationGroup: 'lunge',
    tier: 'secondary',
    capFriendly: true,
    capStrategy: 'unilateral',
  },
  {
    id: 'reverse-lunge',
    name: 'Reverse Lunge',
    movementPattern: 'unilateral',
    primaryMuscles: ['glutes', 'quads'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['dumbbells'],
    locations: ['Work', 'Home'],
    variationGroup: 'lunge',
    tier: 'secondary',
    capFriendly: true,
    capStrategy: 'unilateral',
  },
  {
    id: 'lateral-lunge',
    name: 'Lateral Lunge',
    movementPattern: 'unilateral',
    primaryMuscles: ['quads', 'adductors'],
    secondaryMuscles: ['glutes'],
    equipment: ['dumbbells'],
    locations: ['Work', 'Home'],
    variationGroup: 'lateral-lunge',
    tier: 'accessory',
    capFriendly: true,
    capStrategy: 'unilateral',
  },
  {
    id: 'bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    movementPattern: 'unilateral',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['adductors', 'core'],
    equipment: ['dumbbells', 'bench'],
    locations: ['Work', 'Home'],
    variationGroup: 'split-squat',
    tier: 'primary',
    capFriendly: true,
    capStrategy: 'unilateral',
    loadNotes: 'Brutal with 2x52.5 lb — the single best cap-beating leg builder at Home.',
  },
  {
    id: 'tempo-bulgarian-split-squat',
    name: 'Tempo Bulgarian Split Squat (3s down)',
    movementPattern: 'unilateral',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['core'],
    equipment: ['dumbbells', 'bench'],
    locations: ['Work', 'Home'],
    variationGroup: 'split-squat',
    tier: 'primary',
    capFriendly: true,
    capStrategy: 'tempo',
  },
  {
    id: 'split-squat',
    name: 'Split Squat',
    movementPattern: 'unilateral',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['adductors'],
    equipment: ['dumbbells'],
    locations: ['Work', 'Home'],
    variationGroup: 'split-squat',
    tier: 'secondary',
    capFriendly: true,
    capStrategy: 'unilateral',
  },
  {
    id: 'front-foot-elevated-split-squat',
    name: 'Front-Foot-Elevated Split Squat',
    movementPattern: 'unilateral',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['adductors'],
    equipment: ['dumbbells'],
    locations: ['Work', 'Home'],
    variationGroup: 'split-squat',
    tier: 'secondary',
    capFriendly: true,
    capStrategy: 'elevatedRange',
    loadNotes: 'Extra range at the bottom buys stimulus that the load cap cannot.',
  },
  {
    id: 'step-up',
    name: 'Step-Up',
    movementPattern: 'unilateral',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['calves'],
    equipment: ['dumbbells', 'bench'],
    locations: ['Work', 'Home'],
    variationGroup: 'step-up',
    tier: 'secondary',
    capFriendly: true,
    capStrategy: 'unilateral',
  },
  {
    id: 'deficit-reverse-lunge',
    name: 'Deficit Reverse Lunge',
    movementPattern: 'unilateral',
    primaryMuscles: ['glutes', 'quads'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['dumbbells'],
    locations: ['Work', 'Home'],
    variationGroup: 'lunge',
    tier: 'secondary',
    capFriendly: true,
    capStrategy: 'elevatedRange',
  },
  {
    id: 'single-leg-leg-press',
    name: 'Single-Leg Leg Press',
    movementPattern: 'unilateral',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: [],
    equipment: ['machine'],
    locations: ['Work'],
    variationGroup: 'machine-unilateral',
    tier: 'secondary',
    capStrategy: 'unilateral',
  },

  // ----------------------------------------------------------------- CORE
  {
    id: 'plank',
    metric: 'time',
    name: 'Plank',
    movementPattern: 'core',
    primaryMuscles: ['core'],
    secondaryMuscles: ['shoulders'],
    equipment: ['bodyweight'],
    locations: ['Work', 'Home'],
    variationGroup: 'plank',
    tier: 'accessory',
    capFriendly: true,
  },
  {
    id: 'side-plank',
    metric: 'time',
    name: 'Side Plank',
    movementPattern: 'core',
    primaryMuscles: ['obliques'],
    secondaryMuscles: ['glutes'],
    equipment: ['bodyweight'],
    locations: ['Work', 'Home'],
    variationGroup: 'plank',
    tier: 'accessory',
    capFriendly: true,
  },
  {
    id: 'hollow-body-hold',
    metric: 'time',
    name: 'Hollow Body Hold',
    movementPattern: 'core',
    primaryMuscles: ['core'],
    secondaryMuscles: ['hip flexors'],
    equipment: ['bodyweight'],
    locations: ['Work', 'Home'],
    variationGroup: 'hollow-hold',
    tier: 'accessory',
    capFriendly: true,
  },
  {
    id: 'dead-bug',
    name: 'Dead Bug',
    movementPattern: 'core',
    primaryMuscles: ['core'],
    secondaryMuscles: [],
    equipment: ['bodyweight'],
    locations: ['Work', 'Home'],
    variationGroup: 'anti-extension',
    tier: 'accessory',
    capFriendly: true,
  },
  {
    id: 'bird-dog',
    name: 'Bird Dog',
    movementPattern: 'core',
    primaryMuscles: ['core', 'spinal erectors'],
    secondaryMuscles: ['glutes'],
    equipment: ['bodyweight'],
    locations: ['Work', 'Home'],
    variationGroup: 'anti-extension',
    tier: 'accessory',
    capFriendly: true,
  },
  {
    id: 'hanging-leg-raise',
    name: 'Hanging Leg Raise',
    movementPattern: 'core',
    primaryMuscles: ['core', 'hip flexors'],
    secondaryMuscles: ['forearms'],
    equipment: ['pullupBar'],
    locations: ['Work'],
    variationGroup: 'leg-raise',
    tier: 'accessory',
    capFriendly: true,
  },
  {
    id: 'lying-leg-raise',
    name: 'Lying Leg Raise',
    movementPattern: 'core',
    primaryMuscles: ['core', 'hip flexors'],
    secondaryMuscles: [],
    equipment: ['bodyweight'],
    locations: ['Work', 'Home'],
    variationGroup: 'leg-raise',
    tier: 'accessory',
    capFriendly: true,
  },
  {
    id: 'pallof-press',
    name: 'Pallof Press',
    movementPattern: 'core',
    primaryMuscles: ['obliques', 'core'],
    secondaryMuscles: [],
    equipment: ['cable'],
    locations: ['Work'],
    variationGroup: 'anti-rotation',
    tier: 'accessory',
  },
  {
    id: 'dumbbell-russian-twist',
    name: 'Dumbbell Russian Twist',
    movementPattern: 'core',
    primaryMuscles: ['obliques'],
    secondaryMuscles: ['core'],
    equipment: ['dumbbells'],
    locations: ['Work', 'Home'],
    variationGroup: 'anti-rotation',
    tier: 'accessory',
    capFriendly: true,
    capStrategy: 'highRep',
  },
  {
    id: 'weighted-decline-sit-up',
    name: 'Weighted Decline Sit-Up',
    movementPattern: 'core',
    primaryMuscles: ['core'],
    secondaryMuscles: ['hip flexors'],
    equipment: ['bench', 'dumbbells'],
    locations: ['Work', 'Home'],
    variationGroup: 'sit-up',
    tier: 'accessory',
    capFriendly: true,
  },

  // ---------------------------------------------------------------- CARRY
  {
    id: 'farmers-carry',
    metric: 'time',
    name: "Farmer's Carry",
    movementPattern: 'carry',
    primaryMuscles: ['forearms', 'traps'],
    secondaryMuscles: ['core', 'glutes'],
    equipment: ['dumbbells'],
    locations: ['Work', 'Home'],
    variationGroup: 'farmers-carry',
    tier: 'accessory',
    capFriendly: true,
    capStrategy: 'highRep',
    loadNotes: 'Capped at 52.5 lb/hand — go for distance or time rather than load.',
  },
  {
    id: 'suitcase-carry',
    metric: 'time',
    name: 'Suitcase Carry',
    movementPattern: 'carry',
    primaryMuscles: ['obliques', 'forearms'],
    secondaryMuscles: ['traps', 'core'],
    equipment: ['dumbbells'],
    locations: ['Work', 'Home'],
    variationGroup: 'suitcase-carry',
    tier: 'accessory',
    capFriendly: true,
    capStrategy: 'unilateral',
    loadNotes: 'One-sided load makes the cap a non-issue — the core gives out first.',
  },
  {
    id: 'front-racked-carry',
    metric: 'time',
    name: 'Front-Racked Carry',
    movementPattern: 'carry',
    primaryMuscles: ['core', 'traps'],
    secondaryMuscles: ['front delts'],
    equipment: ['dumbbells'],
    locations: ['Work', 'Home'],
    variationGroup: 'racked-carry',
    tier: 'accessory',
    capFriendly: true,
  },
  {
    id: 'overhead-carry',
    metric: 'time',
    name: 'Overhead Carry',
    movementPattern: 'carry',
    primaryMuscles: ['shoulders', 'core'],
    secondaryMuscles: ['traps'],
    equipment: ['dumbbells'],
    locations: ['Work', 'Home'],
    variationGroup: 'overhead-carry',
    tier: 'accessory',
    capFriendly: true,
  },
];

// -- helpers ---------------------------------------------------------------

export function isAvailableAt(exercise, location) {
  if (!exercise.locations.includes(location)) return false;
  const have = LOCATION_EQUIPMENT[location] ?? [];
  return exercise.equipment.every((token) => have.includes(token));
}

// Dev-time sanity check: catches an exercise tagged for a location that does
// not actually have the required equipment. Run by scripts/check-library.mjs.
export function validateLibrary(library = seedExerciseLibrary) {
  const problems = [];
  const seenIds = new Set();

  for (const ex of library) {
    if (seenIds.has(ex.id)) problems.push(`duplicate id: ${ex.id}`);
    seenIds.add(ex.id);

    if (!MOVEMENT_PATTERNS.includes(ex.movementPattern)) {
      problems.push(`${ex.id}: unknown movementPattern "${ex.movementPattern}"`);
    }
    for (const token of ex.equipment) {
      if (!EQUIPMENT.includes(token)) problems.push(`${ex.id}: unknown equipment "${token}"`);
    }
    for (const loc of ex.locations) {
      const have = LOCATION_EQUIPMENT[loc];
      if (!have) {
        problems.push(`${ex.id}: unknown location "${loc}"`);
        continue;
      }
      const missing = ex.equipment.filter((t) => !have.includes(t));
      if (missing.length) {
        problems.push(`${ex.id}: tagged for ${loc} but ${loc} lacks ${missing.join(', ')}`);
      }
    }
    if (!ex.variationGroup) problems.push(`${ex.id}: missing variationGroup`);
  }

  return problems;
}
